// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function background(color) {
  switch (color) {
    case 0 : 
        return "\x1b[40m";
    case 1 : 
        return "\x1b[44m";
    case 2 : 
        return "\x1b[46m";
    case 3 : 
        return "\x1b[42m";
    case 4 : 
        return "\x1b[45m";
    case 5 : 
        return "\x1b[41m";
    case 6 : 
        return "\x1b[43m";
    case 7 : 
        return "\x1b[47m";
    
  }
}

function foreground(color) {
  switch (color) {
    case 0 : 
        return "\x1b[30m";
    case 1 : 
        return "\x1b[34m";
    case 2 : 
        return "\x1b[36m";
    case 3 : 
        return "\x1b[32m";
    case 4 : 
        return "\x1b[35m";
    case 5 : 
        return "\x1b[31m";
    case 6 : 
        return "\x1b[33m";
    case 7 : 
        return "\x1b[37m";
    
  }
}

function style(style$1) {
  switch (style$1) {
    case 0 : 
        return "\x1b[5m";
    case 1 : 
        return "\x1b[1m";
    case 2 : 
        return "\x1b[2m";
    case 3 : 
        return "\x1b[8m";
    case 4 : 
        return "\x1b[3m";
    case 5 : 
        return "\x1b[0m";
    case 6 : 
        return "\x1b[7m";
    case 7 : 
        return "\x1b[9m";
    case 8 : 
        return "\x1b[4m";
    
  }
}

exports.background = background;
exports.foreground = foreground;
exports.style = style;
/* No side effect */
